status = [
    "Build (ubuntu-latest, stable)",
    "Build (macos-latest, stable)",
    "Build (windows-latest, stable)",
    "Build (ubuntu-latest, beta)",
    "Build (ubuntu-latest, nightly)",
]
block_labels = [
    "invalid",
    "duplicate",
    "blocked",
    "WIP"
]
pr_status = [
    "DCO",
    "CommitCheck",
    "WIP"
]
delete_merged_branches = true
