name: Deploy github pages

on:
  push:
    branches:
      - master

jobs:
  deploy_page:
    name: Deploy Github page
    runs-on: ubuntu-latest
    env:
      MAKE_FEATURES_FLAG: "--all-features"

    steps:
      - uses: actions/checkout@v3
      - name: Setup rust toolchain
        uses: dtolnay/rust-toolchain@nightly
      - name: Install cargo make
        uses: davidB/rust-cargo-make@v1
      - name: Create .env file
        uses: iamsauravsharma/create-dotenv@v1.2.2
        with:
          env-prefix: "MAKE_"
      - name: Generate documentation
        run: |
          cargo make rustdoc --env-file=.env
      - name: Generate index page
        run: |
          echo "<meta http-equiv=refresh content=0;url=alpha_vantage/index.html>" > target/doc/index.html
      - name: Deploy GitHub Page
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: target/doc
