name: Publish release note
on:
  push:
    tags: "v*"

jobs:
  publish_release_note:
    name: Publish release note
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: "1.14"
    - name: Checkout
      uses: actions/checkout@v1
    - name: Generate Release note
      run: |
          go get -u github.com/git-chglog/git-chglog/cmd/git-chglog
          git-chglog $(git describe --tags) > RELEASE_NOTE.md
    - name: Create GitHub release
      uses: softprops/action-gh-release@v1
      with:
        body_path: RELEASE_NOTE.md
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
